### ISSUE TITLE
How to change value to upper case

### ISSUE THREAD

**Issue by jmnamahoe** [jlattimer/CRM-String-Workflow-Utilities#1]
i set a workflow to update the value of field to upper case. but when i try and run 'ToUpper', the step does not seem to run. is there any documentation how-to that goes step-by-step on how to setup the function in a workflow. thanks in advance.

**Comment by jlattimer** [comment]
I'm afraid it doesn't update the value in place. In this case ToUpper returns a value. So you'll need to add an update step after the ToUpper and then look in the bottom of the list of fields in the form assistant on the right hand side for the returned value. Use this value to update the field on the record you passed in.
