### ISSUE TITLE
Title Case not working with All Caps

### ISSUE THREAD

**Issue by Guyanthalas** [jlattimer/CRM-String-Workflow-Utilities#2]
CRM 365 Online, trying to use ToTitleCase on string "RYAN", it stays as "RYAN".

Tested using ToLower, THEN ToTitleCase and it changes to "Ryan".

Not sure if this is a bug or acting as intended. Thanks!

**Comment by jlattimer** [comment]
Yes - I should have indicated this in the wiki page. This is normal behavior as the all caps might be considered an acronym. So the workaround to convert to lower case first is the way to go.
