### ISSUE TITLE
Please add New line char (aka "\n") support for Replase steps

### ISSUE THREAD

**Issue by fvakiliev** [jlattimer/CRM-String-Workflow-Utilities#4]
This would be nice if all the "Find" and "Replace" steps supported the ability to work with "New line" chars. This is useful when manipulating multi-line fields on forms.

Thanks,
FV

**Comment by jlattimer** [comment]
Can you accomplish with this using one of the Regex Replace steps? Maybe this as a pattern? 

/\n/g

**Comment by fvakiliev** [comment]
Hi Jason!
I need to replace one or more **@** symbol in **111@222@@333@@@444** with NewLine char.
I try to use:
String to Search: **111@222@@333@@@444**
Replacement Value: **/\n/**
Pattern: **(@)+**

Result (in multiline text field) is: **111/\n/222/\n/333/\n/444**
but must be:
**111
222
333
444**

What I doing wrong? Show me how, please.

Thanks,
FV

**Comment by fvakiliev** [comment]
Hi Jason. Any suggestion?

**Comment by jlattimer** [comment]
I think I'd need to do something special here to get this to work. Unfortunately not going to be able to get to this immediately.

**Comment by ryannipper** [comment]
Hi Jason,

Just wondering if there is any update on this?  I'd like to be able to replace any instance of more than one newline being added to a multiple lines of text field with a single newline, i.e.:

AAA

BBB


CCC

becomes 

AAA
BBB
CCC

**Comment by steveplatz** [comment]
@ryannipper Something similar to what Jason suggested earlier for @fvakiliev should work for your case. 

String to Search: **AAA\n\nBBB\n\nCCC**
Replacement Value: **\n**
Pattern: **(\n)+**

```
Input:
AAA

BBB

CCC

Result:
AAA
BBB
CCC
```
