### ISSUE TITLE
[Additional Feature] Include "UrlDecode" and "UrlEncode" in next release

### ISSUE THREAD

**Issue by thuld** [jlattimer/CRM-String-Workflow-Utilities#6]
It would be perfect to provide "UrlDecode" and "UrlEncode". We are working with URL and UTM parameters and need to concert `Seminar%20%2811-10-2017%29%3A%20Test%20foobar%20Dynamics%20365` to `Seminar (11-10-2017): Test foobar Dynamics 365` 

In order to support CRM Online, do we need to use `System.Uri.EscapeDataString` instead of `System.Web.HttpUtility`

**Comment by jlattimer** [comment]
Will be in the next release very soon
