### ISSUE TITLE
Replace Space

### ISSUE THREAD

**Issue by tpmeredith** [jlattimer/CRM-String-Workflow-Utilities#9]
Hi, very useful utilities. Other workflow utilities are missing some of this functionality. I love the "Replace" function, however it can't search for a space and replace it with nothing. Would it be hard to add that feature?

**Comment by zabinskie** [comment]
I have a similar need --- I'd like to use "Replace" to search for double spaces and replace them with a single space. That would make an already terrific tool even more awesome!

**Comment by jlattimer** [comment]
Use Regex Replace with Space 
Select the field, 1 for the number of spaces, and for pattern use \s{2}
Then make sure to add another step to take the output of the replace step and update the original field with the new values without double spaces.

**Comment by tpmeredith** [comment]
Thank you Jason!
